name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a tring
        run: echo "Hello, World! seconf"
  parallel-jobs-macos:
    runs-on: macos-latest
    steps:
      - name: echo a string in parallel
        run: echo "This is running in parallel after the first job"
  
  depentent-job:
    runs-on: ubuntu-latest
    needs: run-shell-commands
    steps:
      - name: echo a string after the first job
        run: echo "This job depends on the first job and runs after it"
